POST http://localhost:8000/advertisement
Content-Type: application/json

{
  "title": "Продам ноутбук",
  "description": "Отличное состояние",
  "price": 50000.0,
  "author": "Иван Иванов"
}

GET http://localhost:8000/advertisement/1

GET http://localhost:8000/advertisement?title=ноутбук&min_price=40000

PATCH http://localhost:8000/advertisement/1
Content-Type: application/json

{
  "price": 45000.0
}

DELETE http://localhost:8000/advertisement/1
